### ISSUE TITLE
NETCDF->gtiff georeferencing issue, they do not get added to geoserver

### ISSUE THREAD

**Issue by LukeParky** [GeospatialResearch/Digital-Twins#101]
serve_model.py adds a band from a netcdf file to geoserver.

`add_gtiff_to_geoserver(gtiff_filepath, "dt-model-outputs")` works for .tiff files that are properly georeferenced such as `\\file.canterbury.ac.nz\Research\FloodRiskResearch\DigitalTwin\LISFLOOD-FP\dynamic2_NEWGRID_climate_ARI50_waimakonly_maxdepth1m_rendered.tif`

but does not work for the tiffs created by `convert_nc_to_gtiff(nc_file_path: pathlib.Path) -> pathlib.Path:`
I believe the .nc files are not properly georeferenced, but it could be a problem with the gdal_translate line in this function.

**Comment by caseyli92** [comment]
Hi @LukeParky , I believe this issue has already been addressed in PR #105, close?

**Comment by LukeParky** [comment]
Not so sure about that yet. I think there is still an issue with the georeferencing that I am working on solving. Will link to the PR soon

**Comment by LukeParky** [comment]
This was fixed in #120 by using BG Flood v0.9. Some earlier versions were causing upside down outputs.
