### ISSUE TITLE
Task failed in the backend. Please try again.

### ISSUE THREAD

**Issue by changliao1025** [GeospatialResearch/Digital-Twins#344]
When I tried to run the "Generating model", it always failed with the permission issue. See below log from the terminal: 

Arguments: 'src.tasks.process_dem', 'exc': "PermissionError(13, 'Permission denied')", 'traceback': 'Traceback (most recent call last):\n  File "/venv/lib/python3.11/site-packages/celery/app/trace.py", line 451, in trace_task\n    R = retval = fun(*args, **kwargs)\n                 ^^^^^^^^^^^^^^^^^^^^\n  File "/venv/lib/python3.11/site-packages/celery/app/trace.py", line 734, in __protected_call__\n    return self.run(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/src/tasks.py", line 126, in process_dem\n    process_hydro_dem.main(selected_polygon, **parameters)\n  File "/app/src/flood_model/process_hydro_dem.py", line 106, in main\n    process_dem(selected_polygon_gdf)\n  File "/app/src/flood_model/process_hydro_dem.py", line 62, in process_dem\n    newzealidar.process.main(selected_polygon_gdf)\n  File "/venv/lib/python3.11/site-packages/newzealidar/process.py", line 498, in main\n    utils.save_gpkg(lidar_extent, "lidar_extent")\n  File "/venv/lib/python3.11/site-packages/newzealidar/utils.py", line 994, in save_gpkg\n    pathlib.Path(gpkg_path).mkdir(parents=True, exist_ok=True)\n  File "/venv/lib/python3.11/pathlib.py", line 1116, in mkdir\n    os.mkdir(self, mode)\nPermissionError: [Errno 13] Permission denied: \'/stored_data/gpkg\'\n', 'args': "['POLYGON ((172.71629837906798 -43.40100735095039, 172.71629837906798 -43.38586581746695, 172.67209098399104 -43.38586581746695, 172.67209098399104 -43.40100735095039, 172.71629837906798 -43.40100735095039))']", 'kwargs': '{}', 'description': 'raised unexpected', 'internal': False}

**Comment by LukeParky** [comment]
Hi @changliao1025 thank you, it looks like a regression has caused this. I am investigating now.

**Comment by LukeParky** [comment]
Hi @changliao1025 I believe the issue has been resolved. You will have to pull/build a new image, and I reccomend starting with fresh volumes. 

Eg.
`docker compose pull && docker compose down -v && docker compose up -d && docker compose logs -f backend celery_worker`

**Comment by LukeParky** [comment]
As mentioned in #342, this issue occurs in Ubuntu-22.04 and possibly other operations systems. I am reopening the issue to provide a fix. I believe this is fixed in downstream forks so will try to isolate the fix for this release.

**Comment by LukeParky** [comment]
@changliao1025 please let me know if `git pull && docker compose pull && docker compose down -v && docker compose up -d && docker compose logs -f backend celery_worker` resolves this issue.

**Comment by changliao1025** [comment]
It seems this issue still remains.
<img width="985" alt="Image" src="https://github.com/user-attachments/assets/c5fe3298-d48a-46ce-81ea-bb3a3435d08d" />
I am using an iMac with an Intel processor.

**Comment by LukeParky** [comment]
Hi @changliao1025 it is unfortunate you are still encountering the issue. I am not yet sure how it can be happening.

I have not been able to replicate it since pushing my fix.
I am attempting one more way to replicate this.

Could you please provide me with the contents of your `docker compose images` output?

E.g.
```
CONTAINER                     REPOSITORY                                 TAG                 IMAGE ID            SIZE
backend_digital_twin          lparkinson/flood-resilience-dt             1.4                 ae586e           2.93GB
celery_worker_digital_twin    lparkinson/flood-resilience-dt             1.4                 ae586e           2.93GB
db_postgres_digital_twin      postgis/postgis                            16-3.4              06287eb8e12c        609MB
geoserver_digital_twin        lparkinson/geoserver-flood-resilience-dt   1.4                 efc8ef37f170        1.11GB
message_broker_digital_twin   redis                                      7                   ad4b31aa2de6        117MB
www_digital_twin              lparkinson/www-flood-resilience-dt         1.4                 96b584736ee6        239MB
```

**Comment by LukeParky** [comment]
In addition to the `docker compose images` output could I please also have the output of `docker volume inspect digital-twins_stored_data`?

**Comment by changliao1025** [comment]
This is the output from `docker compose images`:

<img width="845" alt="Image" src="https://github.com/user-attachments/assets/7d6b28e0-9e52-4d55-b917-30e80f00d4d8" />

This is the output from `docker volume inspect digital-twins_stored_data`:
<img width="530" alt="Image" src="https://github.com/user-attachments/assets/1c467483-a16d-48b7-b5ae-3c488eb8f7db" />

**Comment by changliao1025** [comment]
Additional log info:
[2025-04-17 22:14:47,331: CRITICAL/MainProcess] 
celery_worker_digital_twin  | Traceback (most recent call last):
celery_worker_digital_twin  |   File "/venv/lib/python3.11/site-packages/twisted/internet/defer.py", line 2017, in _inlineCallbacks
celery_worker_digital_twin  |     result = context.run(gen.send, result)
celery_worker_digital_twin  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery_worker_digital_twin  |   File "/venv/lib/python3.11/site-packages/scrapy/crawler.py", line 158, in crawl
celery_worker_digital_twin  |     self.engine = self._create_engine()
celery_worker_digital_twin  |                   ^^^^^^^^^^^^^^^^^^^^^
celery_worker_digital_twin  |   File "/venv/lib/python3.11/site-packages/scrapy/crawler.py", line 172, in _create_engine
celery_worker_digital_twin  |     return ExecutionEngine(self, lambda _: self.stop())
celery_worker_digital_twin  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery_worker_digital_twin  |   File "/venv/lib/python3.11/site-packages/scrapy/core/engine.py", line 100, in __init__
celery_worker_digital_twin  |     self.scraper = Scraper(crawler)
celery_worker_digital_twin  |                    ^^^^^^^^^^^^^^^^
celery_worker_digital_twin  |   File "/venv/lib/python3.11/site-packages/scrapy/core/scraper.py", line 109, in __init__
celery_worker_digital_twin  |     self.itemproc: ItemPipelineManager = itemproc_cls.from_crawler(crawler)
celery_worker_digital_twin  |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery_worker_digital_twin  |   File "/venv/lib/python3.11/site-packages/scrapy/middleware.py", line 90, in from_crawler
celery_worker_digital_twin  |     return cls.from_settings(crawler.settings, crawler)
celery_worker_digital_twin  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery_worker_digital_twin  |   File "/venv/lib/python3.11/site-packages/scrapy/middleware.py", line 67, in from_settings
celery_worker_digital_twin  |     mw = create_instance(mwcls, settings, crawler)
celery_worker_digital_twin  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery_worker_digital_twin  |   File "/venv/lib/python3.11/site-packages/scrapy/utils/misc.py", line 188, in create_instance
celery_worker_digital_twin  |     instance = objcls.from_crawler(crawler, *args, **kwargs)
celery_worker_digital_twin  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery_worker_digital_twin  |   File "/venv/lib/python3.11/site-packages/scrapy/pipelines/media.py", line 78, in from_crawler
celery_worker_digital_twin  |     pipe = cls.from_settings(crawler.settings)
celery_worker_digital_twin  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery_worker_digital_twin  |   File "/venv/lib/python3.11/site-packages/scrapy/pipelines/files.py", line 391, in from_settings
celery_worker_digital_twin  |     return cls(store_uri, settings=settings)
celery_worker_digital_twin  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery_worker_digital_twin  |   File "/venv/lib/python3.11/site-packages/scrapy/pipelines/files.py", line 351, in __init__
celery_worker_digital_twin  |     self.store = self._get_store(store_uri)
celery_worker_digital_twin  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
celery_worker_digital_twin  |   File "/venv/lib/python3.11/site-packages/scrapy/pipelines/files.py", line 399, in _get_store
celery_worker_digital_twin  |     return store_cls(uri)
celery_worker_digital_twin  |            ^^^^^^^^^^^^^^
celery_worker_digital_twin  |   File "/venv/lib/python3.11/site-packages/scrapy/pipelines/files.py", line 55, in __init__
celery_worker_digital_twin  |     self._mkdir(Path(self.basedir))
celery_worker_digital_twin  |   File "/venv/lib/python3.11/site-packages/scrapy/pipelines/files.py", line 85, in _mkdir
celery_worker_digital_twin  |     dirname.mkdir(parents=True)
celery_worker_digital_twin  |   File "/venv/lib/python3.11/pathlib.py", line 1116, in mkdir
celery_worker_digital_twin  |     os.mkdir(self, mode)
celery_worker_digital_twin  | PermissionError: [Errno 13] Permission denied: '/stored_data/lidar'

**Comment by LukeParky** [comment]
Hi @changliao1025 and pritamd47

I have pushed a new release with significant changes, that have eliminated the error.

In order to test it you will have to update the `.env` file with some new items from `.env.template` so please follow that process again.

And then run the following commands:
```bash
git pull
docker compose down -v
docker compose pull
docker compose down -v 
docker compose up -d
docker compose logs -f celery_worker
```

Destroying your old docker volumes is very important, because they are corrupted by the previous bug.

**Comment by pritamd47** [comment]
I followed the commands that you shared but I am getting a new error that I didn't see before at the `docker compose logs -f celery_worker` command. Please have a look at the screenshot below -

![Image](https://github.com/user-attachments/assets/6a5eeb49-2f65-4d13-a949-156dfa78014d)

**Comment by LukeParky** [comment]
> I followed the commands that you shared but I am getting a new error that I didn't see before at the `docker compose logs -f celery_worker` command.

I suspect it may be because of a _very_ outdated installation of docker, what version are you running?
My version of Docker is 28.1.1, and the old `docker-compose` command format which I believe that error message is referring to was deprecated in 2023.

If you think that could be the issue, you can learn about migrating docker compose versions here https://docs.docker.com/compose/releases/migrate/.

It may have minor impacts on other `docker-compose.yml` files on the system.

**Comment by pritamd47** [comment]
@LukeParky , that was the issue. I updated docker and docker-compose ran.

Now I am hitting this error while running the model. Here is what I did - 
1. I selected a region with shift+click-dragging
2. I clicked on explore data > "Model a flood scenario" where I got this error:

![Image](https://github.com/user-attachments/assets/d8da49b5-70ed-4f14-b6b7-95bc753d09e3)

Here are the latest logs from celery_worker:

![Image](https://github.com/user-attachments/assets/43884a9a-1e8d-44b2-990e-9ce9b70a89ee)

**Comment by pritamd47** [comment]
Here is the log file: [log_001.txt](https://github.com/user-attachments/files/20359906/log_001.txt)

Here is the screenshot of the page. I have tried restarting, but the same issue persists.
![Image](https://github.com/user-attachments/assets/78609289-678d-4177-9657-cf181295ec5f)

**Comment by LukeParky** [comment]
> Hi [@LukeParky](https://github.com/LukeParky) , any ideas on what could be causing this?

@pritamd47 It appears to happen on the pushed images and not on my built images. These should be exactly the same. I'm doing some tracing and will work out why this is the case, and I will get back to you. Docker is meant to solve this exact problem so it surprises me that it is causing issues here.

The issue is once again the permission error on `/stored_data/lidar`

**Comment by LukeParky** [comment]
Update: I am testing a solution on https://github.com/GeospatialResearch/Digital-Twins/pull/356 but the only thing I have done is rebuilt the image. I won't be able to fully test this until roughly Wednesday next week.

**Comment by LukeParky** [comment]
@pritamd47 sorry for the large delay, I was off sick and was not able to complete the testing on schedule.

I have completed the testing and the software is ready to be run again.
Once again, pull the latest changes and restart services with:
```bash
git pull
docker compose down -v
docker compose pull
docker compose down -v 
docker compose up -d
docker compose logs -f celery_worker
```

The software is ready to continue review, could you please continue your review?

**Comment by LukeParky** [comment]
@pritamd47 to confirm, what operating system are you using? I believe you were using Windows 10 Docker Desktop WSL with Ubuntu, is that correct?

**Comment by pritamd47** [comment]
Yes, that is correct.

**Comment by LukeParky** [comment]
So I can confirm on the same setup that the problem was occurring, but I couldn't understand since I had been building from the same source in my testing.

It turns out that the Windows WSL images are not compatible with the Linux ones. I've never heard of this issue before but I resolved it by removing the ability to pull images.

**Comment by changliao1025** [comment]
I removed the Docker image and reran the model, I got some different errors. See both the log text file and the screenshot:

<img width="1808" alt="Image" src="https://github.com/user-attachments/assets/5acef612-d4d0-4211-a0b6-3c86f1412cf8" />

[log.txt](https://github.com/user-attachments/files/20908632/log.txt)

**Comment by LukeParky** [comment]
@changliao1025 What operating system are you using?

**Comment by changliao1025** [comment]
I am using macOS Sequoia on a iMac Pro with Intel CPU.

**Comment by pritamd47** [comment]
Hi @LukeParky, have the dependencies been changed? My WSL is failing everytime at this step. Apologies for the delay, I wanted to make sure that the problem persists and is not a one off thing related to my setup.
Here's a screenshot where you can see at which step the issue arises.

![Image](https://github.com/user-attachments/assets/c31b4711-b89b-49aa-9e6e-3a176ce5b5ac)
